### ISSUE TITLE
Bug and Miss CSS on CaAs Features

### ISSUE THREAD

**Issue by adhiiimf** [Daskom-Lab/daskomrec22#11]
## FINAL PLOT VIEW [CAAS]
![image](https://user-images.githubusercontent.com/66113867/160177001-822fa039-d732-413d-a2e2-07b68a2757ab.png)
`Desc:`
Pada halaman tersebut, styling css nya belum disesuaikan.

## CEK LULUS VIEW [CAAS]
![image](https://user-images.githubusercontent.com/66113867/160177135-fff5bdf0-2e94-480e-b0fb-c6d717bbfb89.png)
`Desc:`
Pada halaman tersebut, styling buat text lulus atau text tidak lulus styling nya dimasukkan ke `div` saja, jangan ke  class di `span`.
- Example:
```html
<div class="cssClassForbackgroundColor">
  <span class="...">content text lulus nya</span>
</div>
``` 
Kemudian ada satu branch condition yang harus diperbaiki yaitu: 
- From 
```php
$isPlotActive===0
```
- To
```php
$isPlotActive!==0
```

## LIST PLOT VIEW [CAAS]
![image](https://user-images.githubusercontent.com/66113867/160176676-8158c0e5-8351-4318-92cd-cf068b5f4e9d.png)
`Desc:`
Pada halaman tersebut, styling css nya belum disesuaikan.

Mungkin itu beberapa issue untuk akun CAAS rekrutmen daskom 20222, terima kasih, semangat dipo!

devkom'19,
_Adhi MF_

**Comment by fakhrip** [comment]
Oh ya btw kalau ini kan ada issue nih, ntar pas bikin PR di title PR nya tag issue nya ya @Soedipo (contohnya ini kan tag number nya #11 ya, berarti nanti title PR nya, "Blablabla (Fix #11)")

Jadi nanti issue ini otomatis ke close pas Pr nya dah merged

**Comment by Soedipo** [comment]
> Oh ya btw kalau ini kan ada issue nih, ntar pas bikin PR di title PR nya tag issue nya ya @Soedipo (contohnya ini kan tag number nya #11 ya, berarti nanti title PR nya, "Blablabla (Fix #11)")
> 
> Jadi nanti issue ini otomatis ke close pas Pr nya dah merged

oke banggg
